package merchantbusinessapimapper

import (
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/merchant_business"
	"github.com/MamangRust/microservice-ecommerce-shared/domain/response"
)

type MerchantBusinessBaseResponseMapper interface {
	ToResponseMerchantBusiness(merchant *pb_merchant_business.MerchantBusinessResponse) *response.MerchantBusinessResponse
	ToResponsesMerchantBusiness(merchants []*pb_merchant_business.MerchantBusinessResponse) []*response.MerchantBusinessResponse
	ToApiResponseMerchantBusiness(pbResponse *pb_merchant_business.ApiResponseMerchantBusiness) *response.ApiResponseMerchantBusiness
}

type MerchantBusinessQueryResponseMapper interface {
	MerchantBusinessBaseResponseMapper
	ToApiResponsesMerchantBusiness(pbResponse *pb_merchant_business.ApiResponsesMerchantBusiness) *response.ApiResponsesMerchantBusiness
	ToApiResponsePaginationMerchantBusiness(pbResponse *pb_merchant_business.ApiResponsePaginationMerchantBusiness) *response.ApiResponsePaginationMerchantBusiness
	ToApiResponsePaginationMerchantBusinessDeleteAt(pbResponse *pb_merchant_business.ApiResponsePaginationMerchantBusinessDeleteAt) *response.ApiResponsePaginationMerchantBusinessDeleteAt
}

type MerchantBusinessCommandResponseMapper interface {
	MerchantBusinessBaseResponseMapper
	ToResponseMerchantBusinessDeleteAt(merchant *pb_merchant_business.MerchantBusinessResponseDeleteAt) *response.MerchantBusinessResponseDeleteAt
	ToResponsesMerchantBusinessDeleteAt(merchants []*pb_merchant_business.MerchantBusinessResponseDeleteAt) []*response.MerchantBusinessResponseDeleteAt
	ToApiResponseMerchantBusinessDeleteAt(pbResponse *pb_merchant_business.ApiResponseMerchantBusinessDeleteAt) *response.ApiResponseMerchantBusinessDeleteAt
}
