package merchantawardapimapper

import (
	"github.com/MamangRust/microservice-ecommerce-grpc-pb/merchant_award"
	"github.com/MamangRust/microservice-ecommerce-shared/domain/response"
)

type MerchantAwardBaseResponseMapper interface {
	ToResponseMerchantAward(MerchantAward *pb_merchant_award.MerchantAwardResponse) *response.MerchantAwardResponse
	ToResponsesMerchantAward(MerchantAwards []*pb_merchant_award.MerchantAwardResponse) []*response.MerchantAwardResponse
	ToApiResponseMerchantAward(pbResponse *pb_merchant_award.ApiResponseMerchantAward) *response.ApiResponseMerchantAward
}

type MerchantAwardQueryResponseMapper interface {
	MerchantAwardBaseResponseMapper
	ToApiResponsesMerchantAward(pbResponse *pb_merchant_award.ApiResponsesMerchantAward) *response.ApiResponsesMerchantAward
	ToApiResponsePaginationMerchantAward(pbResponse *pb_merchant_award.ApiResponsePaginationMerchantAward) *response.ApiResponsePaginationMerchantAward
	ToApiResponsePaginationMerchantAwardDeleteAt(pbResponse *pb_merchant_award.ApiResponsePaginationMerchantAwardDeleteAt) *response.ApiResponsePaginationMerchantAwardDeleteAt
}

type MerchantAwardCommandResponseMapper interface {
	MerchantAwardBaseResponseMapper
	ToResponseMerchantAwardDeleteAt(MerchantAward *pb_merchant_award.MerchantAwardResponseDeleteAt) *response.MerchantAwardResponseDeleteAt
	ToResponsesMerchantAwardDeleteAt(MerchantAwards []*pb_merchant_award.MerchantAwardResponseDeleteAt) []*response.MerchantAwardResponseDeleteAt
	ToApiResponseMerchantAwardDeleteAt(pbResponse *pb_merchant_award.ApiResponseMerchantAwardDeleteAt) *response.ApiResponseMerchantAwardDeleteAt
}
