// Code generated by the cross-service DTO refactor; DO NOT EDIT by hand.
//
// These structs mirror the generated query result/model types of OTHER
// services. The owning service generates them from its own queries; consuming
// services build them from gRPC responses and must keep this file in sync with
// the owner's generated types.
package dto

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GetProductByIDRow struct {
	ProductID    int32            `json:"product_id"`
	MerchantID   int32            `json:"merchant_id"`
	CategoryID   int32            `json:"category_id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Price        int32            `json:"price"`
	CountInStock int32            `json:"count_in_stock"`
	Brand        *string          `json:"brand"`
	Weight       *int32           `json:"weight"`
	Rating       *float64         `json:"rating"`
	SlugProduct  *string          `json:"slug_product"`
	ImageProduct *string          `json:"image_product"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type GetUserByIDRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
