// Code generated by the cross-service DTO refactor; DO NOT EDIT by hand.
//
// These structs mirror the generated query result/model types of OTHER
// services. The owning service generates them from its own queries; consuming
// services build them from gRPC responses and must keep this file in sync with
// the owner's generated types.
package dto

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateUserRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type GetUserByEmailAndVerifyRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type GetUserByIDRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type GetUserByVerificationCodeRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	RoleID    int32            `json:"role_id"`
	RoleName  string           `json:"role_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type UpdateUserIsVerifiedRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UpdateUserPasswordRow struct {
	UserID    int32            `json:"user_id"`
	Firstname string           `json:"firstname"`
	Lastname  string           `json:"lastname"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	UserID           int32            `json:"user_id"`
	Firstname        string           `json:"firstname"`
	Lastname         string           `json:"lastname"`
	Email            string           `json:"email"`
	Password         string           `json:"password"`
	VerificationCode string           `json:"verification_code"`
	IsVerified       *bool            `json:"is_verified"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type UserRole struct {
	UserRoleID int32            `json:"user_role_id"`
	UserID     int32            `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}
