// Code generated by the cross-service DTO refactor; DO NOT EDIT by hand.
//
// These structs mirror the generated query result/model types of OTHER
// services. The owning service generates them from its own queries; consuming
// services build them from gRPC responses and must keep this file in sync with
// the owner's generated types.
package dto

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GetCategoryByIDRow struct {
	CategoryID    int32            `json:"category_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	SlugCategory  *string          `json:"slug_category"`
	ImageCategory *string          `json:"image_category"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type GetMerchantByIDRow struct {
	MerchantID   int32            `json:"merchant_id"`
	UserID       int32            `json:"user_id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Address      *string          `json:"address"`
	ContactEmail *string          `json:"contact_email"`
	ContactPhone *string          `json:"contact_phone"`
	Status       string           `json:"status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
